// <auto-generated />
namespace SWGOH.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CharacterClassifiers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CharacterClassifiers));
        
        string IMigrationMetadata.Id
        {
            get { return "201710221649549_CharacterClassifiers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
