namespace SWGOH.Web.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Rewrite : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.TerritoryPlatoons", "Character1_Id", "dbo.Characters");
            DropForeignKey("dbo.TerritoryPlatoons", "Character10_Id", "dbo.Characters");
            DropForeignKey("dbo.TerritoryPlatoons", "Character10Member_Id", "dbo.Members");
            DropForeignKey("dbo.TerritoryPlatoons", "Character11_Id", "dbo.Characters");
            DropForeignKey("dbo.TerritoryPlatoons", "Character11Member_Id", "dbo.Members");
            DropForeignKey("dbo.TerritoryPlatoons", "Character12_Id", "dbo.Characters");
            DropForeignKey("dbo.TerritoryPlatoons", "Character12Member_Id", "dbo.Members");
            DropForeignKey("dbo.TerritoryPlatoons", "Character13_Id", "dbo.Characters");
            DropForeignKey("dbo.TerritoryPlatoons", "Character13Member_Id", "dbo.Members");
            DropForeignKey("dbo.TerritoryPlatoons", "Character14_Id", "dbo.Characters");
            DropForeignKey("dbo.TerritoryPlatoons", "Character14Member_Id", "dbo.Members");
            DropForeignKey("dbo.TerritoryPlatoons", "Character15_Id", "dbo.Characters");
            DropForeignKey("dbo.TerritoryPlatoons", "Character15Member_Id", "dbo.Members");
            DropForeignKey("dbo.TerritoryPlatoons", "Character1Member_Id", "dbo.Members");
            DropForeignKey("dbo.TerritoryPlatoons", "Character2_Id", "dbo.Characters");
            DropForeignKey("dbo.TerritoryPlatoons", "Character2Member_Id", "dbo.Members");
            DropForeignKey("dbo.TerritoryPlatoons", "Character3_Id", "dbo.Characters");
            DropForeignKey("dbo.TerritoryPlatoons", "Character3Member_Id", "dbo.Members");
            DropForeignKey("dbo.TerritoryPlatoons", "Character4_Id", "dbo.Characters");
            DropForeignKey("dbo.TerritoryPlatoons", "Character4Member_Id", "dbo.Members");
            DropForeignKey("dbo.TerritoryPlatoons", "Character5_Id", "dbo.Characters");
            DropForeignKey("dbo.TerritoryPlatoons", "Character5Member_Id", "dbo.Members");
            DropForeignKey("dbo.TerritoryPlatoons", "Character6_Id", "dbo.Characters");
            DropForeignKey("dbo.TerritoryPlatoons", "Character6Member_Id", "dbo.Members");
            DropForeignKey("dbo.TerritoryPlatoons", "Character7_Id", "dbo.Characters");
            DropForeignKey("dbo.TerritoryPlatoons", "Character7Member_Id", "dbo.Members");
            DropForeignKey("dbo.TerritoryPlatoons", "Character8_Id", "dbo.Characters");
            DropForeignKey("dbo.TerritoryPlatoons", "Character8Member_Id", "dbo.Members");
            DropForeignKey("dbo.TerritoryPlatoons", "Character9_Id", "dbo.Characters");
            DropForeignKey("dbo.TerritoryPlatoons", "Character9Member_Id", "dbo.Members");
            DropForeignKey("dbo.PhaseTerritories", "TerritoryPlatoon1_Id", "dbo.TerritoryPlatoons");
            DropForeignKey("dbo.PhaseTerritories", "TerritoryPlatoon2_Id", "dbo.TerritoryPlatoons");
            DropForeignKey("dbo.PhaseTerritories", "TerritoryPlatoon3_Id", "dbo.TerritoryPlatoons");
            DropForeignKey("dbo.PhaseTerritories", "TerritoryPlatoon4_Id", "dbo.TerritoryPlatoons");
            DropForeignKey("dbo.PhaseTerritories", "TerritoryPlatoon5_Id", "dbo.TerritoryPlatoons");
            DropForeignKey("dbo.PhaseTerritories", "TerritoryPlatoon6_Id", "dbo.TerritoryPlatoons");
            DropForeignKey("dbo.TerritoryBattlePhases", "Territory1_Id", "dbo.PhaseTerritories");
            DropForeignKey("dbo.TerritoryBattlePhases", "Territory2_Id", "dbo.PhaseTerritories");
            DropForeignKey("dbo.TerritoryBattles", "Phase1_Id", "dbo.TerritoryBattlePhases");
            DropForeignKey("dbo.TerritoryBattles", "Phase2_Id", "dbo.TerritoryBattlePhases");
            DropForeignKey("dbo.TerritoryBattles", "Phase3_Id", "dbo.TerritoryBattlePhases");
            DropForeignKey("dbo.TerritoryBattles", "Phase4_Id", "dbo.TerritoryBattlePhases");
            DropForeignKey("dbo.TerritoryBattles", "Phase5_Id", "dbo.TerritoryBattlePhases");
            DropForeignKey("dbo.TerritoryBattles", "Phase6_Id", "dbo.TerritoryBattlePhases");
            DropIndex("dbo.PhaseTerritories", new[] { "TerritoryPlatoon1_Id" });
            DropIndex("dbo.PhaseTerritories", new[] { "TerritoryPlatoon2_Id" });
            DropIndex("dbo.PhaseTerritories", new[] { "TerritoryPlatoon3_Id" });
            DropIndex("dbo.PhaseTerritories", new[] { "TerritoryPlatoon4_Id" });
            DropIndex("dbo.PhaseTerritories", new[] { "TerritoryPlatoon5_Id" });
            DropIndex("dbo.PhaseTerritories", new[] { "TerritoryPlatoon6_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character1_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character2_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character3_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character4_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character5_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character6_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character7_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character8_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character9_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character10_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character11_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character12_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character13_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character14_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character15_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character1Member_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character2Member_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character3Member_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character4Member_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character5Member_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character6Member_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character7Member_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character8Member_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character9Member_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character10Member_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character11Member_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character12Member_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character13Member_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character14Member_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "Character15Member_Id" });
            DropIndex("dbo.TerritoryBattlePhases", new[] { "Territory1_Id" });
            DropIndex("dbo.TerritoryBattlePhases", new[] { "Territory2_Id" });
            DropIndex("dbo.TerritoryBattles", new[] { "Phase1_Id" });
            DropIndex("dbo.TerritoryBattles", new[] { "Phase2_Id" });
            DropIndex("dbo.TerritoryBattles", new[] { "Phase3_Id" });
            DropIndex("dbo.TerritoryBattles", new[] { "Phase4_Id" });
            DropIndex("dbo.TerritoryBattles", new[] { "Phase5_Id" });
            DropIndex("dbo.TerritoryBattles", new[] { "Phase6_Id" });
            CreateTable(
                "dbo.PlatoonCharacters",
                c => new
                    {
                        Id = c.Guid(nullable: false),
                        Character_Id = c.Guid(nullable: false),
                        TerritoryPlatoon_Id = c.Guid(),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.Characters", t => t.Character_Id, cascadeDelete: true)
                .ForeignKey("dbo.TerritoryPlatoons", t => t.TerritoryPlatoon_Id)
                .Index(t => t.Character_Id)
                .Index(t => t.TerritoryPlatoon_Id);
            
            AddColumn("dbo.PhaseTerritories", "PhaseLocation", c => c.String());
            AddColumn("dbo.PhaseTerritories", "TerritoryBattlePhase_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "PlatoonNumber", c => c.Int(nullable: false));
            AddColumn("dbo.TerritoryPlatoons", "PhaseTerritory_Id", c => c.Guid());
            AddColumn("dbo.TerritoryBattlePhases", "Phase", c => c.Int(nullable: false));
            AddColumn("dbo.TerritoryBattlePhases", "TerritoryBattle_Id", c => c.Guid());
            CreateIndex("dbo.PhaseTerritories", "TerritoryBattlePhase_Id");
            CreateIndex("dbo.TerritoryPlatoons", "PhaseTerritory_Id");
            CreateIndex("dbo.TerritoryBattlePhases", "TerritoryBattle_Id");
            AddForeignKey("dbo.TerritoryPlatoons", "PhaseTerritory_Id", "dbo.PhaseTerritories", "Id");
            AddForeignKey("dbo.PhaseTerritories", "TerritoryBattlePhase_Id", "dbo.TerritoryBattlePhases", "Id");
            AddForeignKey("dbo.TerritoryBattlePhases", "TerritoryBattle_Id", "dbo.TerritoryBattles", "Id");
            DropColumn("dbo.PhaseTerritories", "TerritoryPlatoon1_Id");
            DropColumn("dbo.PhaseTerritories", "TerritoryPlatoon2_Id");
            DropColumn("dbo.PhaseTerritories", "TerritoryPlatoon3_Id");
            DropColumn("dbo.PhaseTerritories", "TerritoryPlatoon4_Id");
            DropColumn("dbo.PhaseTerritories", "TerritoryPlatoon5_Id");
            DropColumn("dbo.PhaseTerritories", "TerritoryPlatoon6_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character1_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character2_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character3_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character4_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character5_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character6_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character7_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character8_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character9_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character10_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character11_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character12_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character13_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character14_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character15_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character1Member_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character2Member_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character3Member_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character4Member_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character5Member_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character6Member_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character7Member_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character8Member_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character9Member_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character10Member_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character11Member_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character12Member_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character13Member_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character14Member_Id");
            DropColumn("dbo.TerritoryPlatoons", "Character15Member_Id");
            DropColumn("dbo.TerritoryBattlePhases", "Territory1_Id");
            DropColumn("dbo.TerritoryBattlePhases", "Territory2_Id");
            DropColumn("dbo.TerritoryBattles", "Phase1_Id");
            DropColumn("dbo.TerritoryBattles", "Phase2_Id");
            DropColumn("dbo.TerritoryBattles", "Phase3_Id");
            DropColumn("dbo.TerritoryBattles", "Phase4_Id");
            DropColumn("dbo.TerritoryBattles", "Phase5_Id");
            DropColumn("dbo.TerritoryBattles", "Phase6_Id");
        }
        
        public override void Down()
        {
            AddColumn("dbo.TerritoryBattles", "Phase6_Id", c => c.Guid());
            AddColumn("dbo.TerritoryBattles", "Phase5_Id", c => c.Guid());
            AddColumn("dbo.TerritoryBattles", "Phase4_Id", c => c.Guid());
            AddColumn("dbo.TerritoryBattles", "Phase3_Id", c => c.Guid());
            AddColumn("dbo.TerritoryBattles", "Phase2_Id", c => c.Guid());
            AddColumn("dbo.TerritoryBattles", "Phase1_Id", c => c.Guid());
            AddColumn("dbo.TerritoryBattlePhases", "Territory2_Id", c => c.Guid());
            AddColumn("dbo.TerritoryBattlePhases", "Territory1_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character15Member_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character14Member_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character13Member_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character12Member_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character11Member_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character10Member_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character9Member_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character8Member_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character7Member_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character6Member_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character5Member_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character4Member_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character3Member_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character2Member_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character1Member_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character15_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character14_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character13_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character12_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character11_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character10_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character9_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character8_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character7_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character6_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character5_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character4_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character3_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character2_Id", c => c.Guid());
            AddColumn("dbo.TerritoryPlatoons", "Character1_Id", c => c.Guid());
            AddColumn("dbo.PhaseTerritories", "TerritoryPlatoon6_Id", c => c.Guid());
            AddColumn("dbo.PhaseTerritories", "TerritoryPlatoon5_Id", c => c.Guid());
            AddColumn("dbo.PhaseTerritories", "TerritoryPlatoon4_Id", c => c.Guid());
            AddColumn("dbo.PhaseTerritories", "TerritoryPlatoon3_Id", c => c.Guid());
            AddColumn("dbo.PhaseTerritories", "TerritoryPlatoon2_Id", c => c.Guid());
            AddColumn("dbo.PhaseTerritories", "TerritoryPlatoon1_Id", c => c.Guid());
            DropForeignKey("dbo.TerritoryBattlePhases", "TerritoryBattle_Id", "dbo.TerritoryBattles");
            DropForeignKey("dbo.PhaseTerritories", "TerritoryBattlePhase_Id", "dbo.TerritoryBattlePhases");
            DropForeignKey("dbo.TerritoryPlatoons", "PhaseTerritory_Id", "dbo.PhaseTerritories");
            DropForeignKey("dbo.PlatoonCharacters", "TerritoryPlatoon_Id", "dbo.TerritoryPlatoons");
            DropForeignKey("dbo.PlatoonCharacters", "Character_Id", "dbo.Characters");
            DropIndex("dbo.TerritoryBattlePhases", new[] { "TerritoryBattle_Id" });
            DropIndex("dbo.PlatoonCharacters", new[] { "TerritoryPlatoon_Id" });
            DropIndex("dbo.PlatoonCharacters", new[] { "Character_Id" });
            DropIndex("dbo.TerritoryPlatoons", new[] { "PhaseTerritory_Id" });
            DropIndex("dbo.PhaseTerritories", new[] { "TerritoryBattlePhase_Id" });
            DropColumn("dbo.TerritoryBattlePhases", "TerritoryBattle_Id");
            DropColumn("dbo.TerritoryBattlePhases", "Phase");
            DropColumn("dbo.TerritoryPlatoons", "PhaseTerritory_Id");
            DropColumn("dbo.TerritoryPlatoons", "PlatoonNumber");
            DropColumn("dbo.PhaseTerritories", "TerritoryBattlePhase_Id");
            DropColumn("dbo.PhaseTerritories", "PhaseLocation");
            DropTable("dbo.PlatoonCharacters");
            CreateIndex("dbo.TerritoryBattles", "Phase6_Id");
            CreateIndex("dbo.TerritoryBattles", "Phase5_Id");
            CreateIndex("dbo.TerritoryBattles", "Phase4_Id");
            CreateIndex("dbo.TerritoryBattles", "Phase3_Id");
            CreateIndex("dbo.TerritoryBattles", "Phase2_Id");
            CreateIndex("dbo.TerritoryBattles", "Phase1_Id");
            CreateIndex("dbo.TerritoryBattlePhases", "Territory2_Id");
            CreateIndex("dbo.TerritoryBattlePhases", "Territory1_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character15Member_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character14Member_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character13Member_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character12Member_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character11Member_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character10Member_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character9Member_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character8Member_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character7Member_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character6Member_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character5Member_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character4Member_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character3Member_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character2Member_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character1Member_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character15_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character14_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character13_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character12_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character11_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character10_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character9_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character8_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character7_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character6_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character5_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character4_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character3_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character2_Id");
            CreateIndex("dbo.TerritoryPlatoons", "Character1_Id");
            CreateIndex("dbo.PhaseTerritories", "TerritoryPlatoon6_Id");
            CreateIndex("dbo.PhaseTerritories", "TerritoryPlatoon5_Id");
            CreateIndex("dbo.PhaseTerritories", "TerritoryPlatoon4_Id");
            CreateIndex("dbo.PhaseTerritories", "TerritoryPlatoon3_Id");
            CreateIndex("dbo.PhaseTerritories", "TerritoryPlatoon2_Id");
            CreateIndex("dbo.PhaseTerritories", "TerritoryPlatoon1_Id");
            AddForeignKey("dbo.TerritoryBattles", "Phase6_Id", "dbo.TerritoryBattlePhases", "Id");
            AddForeignKey("dbo.TerritoryBattles", "Phase5_Id", "dbo.TerritoryBattlePhases", "Id");
            AddForeignKey("dbo.TerritoryBattles", "Phase4_Id", "dbo.TerritoryBattlePhases", "Id");
            AddForeignKey("dbo.TerritoryBattles", "Phase3_Id", "dbo.TerritoryBattlePhases", "Id");
            AddForeignKey("dbo.TerritoryBattles", "Phase2_Id", "dbo.TerritoryBattlePhases", "Id");
            AddForeignKey("dbo.TerritoryBattles", "Phase1_Id", "dbo.TerritoryBattlePhases", "Id");
            AddForeignKey("dbo.TerritoryBattlePhases", "Territory2_Id", "dbo.PhaseTerritories", "Id");
            AddForeignKey("dbo.TerritoryBattlePhases", "Territory1_Id", "dbo.PhaseTerritories", "Id");
            AddForeignKey("dbo.PhaseTerritories", "TerritoryPlatoon6_Id", "dbo.TerritoryPlatoons", "Id");
            AddForeignKey("dbo.PhaseTerritories", "TerritoryPlatoon5_Id", "dbo.TerritoryPlatoons", "Id");
            AddForeignKey("dbo.PhaseTerritories", "TerritoryPlatoon4_Id", "dbo.TerritoryPlatoons", "Id");
            AddForeignKey("dbo.PhaseTerritories", "TerritoryPlatoon3_Id", "dbo.TerritoryPlatoons", "Id");
            AddForeignKey("dbo.PhaseTerritories", "TerritoryPlatoon2_Id", "dbo.TerritoryPlatoons", "Id");
            AddForeignKey("dbo.PhaseTerritories", "TerritoryPlatoon1_Id", "dbo.TerritoryPlatoons", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character9Member_Id", "dbo.Members", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character9_Id", "dbo.Characters", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character8Member_Id", "dbo.Members", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character8_Id", "dbo.Characters", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character7Member_Id", "dbo.Members", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character7_Id", "dbo.Characters", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character6Member_Id", "dbo.Members", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character6_Id", "dbo.Characters", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character5Member_Id", "dbo.Members", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character5_Id", "dbo.Characters", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character4Member_Id", "dbo.Members", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character4_Id", "dbo.Characters", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character3Member_Id", "dbo.Members", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character3_Id", "dbo.Characters", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character2Member_Id", "dbo.Members", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character2_Id", "dbo.Characters", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character1Member_Id", "dbo.Members", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character15Member_Id", "dbo.Members", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character15_Id", "dbo.Characters", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character14Member_Id", "dbo.Members", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character14_Id", "dbo.Characters", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character13Member_Id", "dbo.Members", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character13_Id", "dbo.Characters", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character12Member_Id", "dbo.Members", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character12_Id", "dbo.Characters", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character11Member_Id", "dbo.Members", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character11_Id", "dbo.Characters", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character10Member_Id", "dbo.Members", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character10_Id", "dbo.Characters", "Id");
            AddForeignKey("dbo.TerritoryPlatoons", "Character1_Id", "dbo.Characters", "Id");
        }
    }
}
